name: GitHub Actions Vercel 生产部署

# 环境变量：Vercel账号ID、项目ID
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

# 触发条件：向main分支发起的PR被合并（closed且merged为true）
on:
  pull_request:
    branches: [ "main" ]
    types:
      - closed

jobs:
  # 仅当PR被合并时运行测试
  Test:
    if: github.event.pull_request.merged == true # 条件：PR已合并
    uses: jcchenaut/my-next-app/.github/workflows/test.yml@develop # 替换为你的GitHub账号/仓库名和分支

  # 测试通过后执行生产部署
  Deploy-Production:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    needs: [Test]
    steps:
      - uses: actions/checkout@v3
      
      - name: 安装Vercel CLI
        run: npm install --global vercel@canary
      
      - name: 获取Vercel环境信息（生产环境）
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      
      - name: 构建项目产物（生产环境）
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      
      - name: 部署项目产物到Vercel（生产环境）
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}