name: GitHub Actions Vercel 预览部署

# 环境变量：Vercel账号ID、项目ID（从GitHub Secrets中获取）
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

# 触发条件：手动触发
on:
  workflow_dispatch:

jobs:
  # 先运行测试工作流（复用test.yml）
  Test:
    uses: jcchenaut/my-next-app/.github/workflows/test.yml@develop # 替换为你的GitHub账号/仓库名和分支

  # 测试通过后执行预览部署
  Deploy-Preview:
    runs-on: ubuntu-latest
    needs: [Test] # 依赖Test任务，需Test完成后才执行
    steps:
      - uses: actions/checkout@v3 # 检出代码
      
      - name: 安装Vercel CLI
        run: npm install --global vercel@canary # 安装Vercel CLI（预览版）
      
      - name: 获取Vercel环境信息
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }} # 从Vercel拉取预览环境配置
      
      - name: 构建项目产物
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      
      - name: 部署项目产物到Vercel（预览环境）
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}