name: CI_action

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: |
        cd worksheet2/my-nest-app
        npm ci

    - name: Run the tests
      run: |
        cd worksheet2/my-nest-app
        npx ts-jest config:init
        npm test

    - name: Build
      run: |
        cd worksheet2/my-nest-app
        npm run build
